Ongoing work on the `rlx` authentication handling.

diff --git a/bin/rlx b/bin/rlx
--- a/bin/rlx
+++ b/bin/rlx
@@ -15,6 +15,7 @@ Allows manipulation and querying of couchdb(7) databases from the command line.
 ## USAGE
 
 	rlx command [options...]
+	rlx shell host
 	
 ## FILES
 
@@ -77,7 +78,10 @@ help.parse "$@";
 # 	exit 0;
 # fi
 
-rlx_home="$HOME/.rlx";
+declare -g rlx_prompt="rlx %s";
+declare -g rlx_prompt_suffix=" ⚡ ";
+
+declare -g rlx_home="$HOME/.rlx";
 
 function rlx.init {
 	local db="db";
@@ -121,9 +125,66 @@ function rlx.firstrun? {
 	test -d "$rlx_home";
 }
 
+function rlx.prompt {
+	local replace="${1:-}";
+	local ps1=$( printf "$rlx_prompt" "$replace" );
+	echo -n "${ps1}${rlx_prompt_suffix}";
+}
+
+function rlx.shell {
+	echo "$FUNCNAME : $*";
+	
+	host="${1:-}";
+	
+	# TODO: add prompt to specify the host?
+	if [ $# -eq 0 ]; then
+		console.quit 1 "no host specified";
+	fi
+	
+	# TODO: test if db-name has been specified
+	
+	# /_all_dbs
+	# ["fastdrop","hosts","rlx-world-writable"]
+	
+	console.info "host %s" "$host";
+	couchdb.db.list "$host";
+	
+	rlx.response;
+	
+	#echo "got response status: $http_response_status";
+}
+
+# handle a server response
+function rlx.response {
+	if [ $http_response_status -eq 401 ]; then
+		console.warn "authorization required for %s" "$host";
+		
+		#if [ -n "$PS1" ]
+		if [ -v PS1 ]   # On Bash 4.2+ ...
+		then
+		  # non-interactive
+			echo "got non-interactive ..."
+		else
+		  # interactive
+			#echo "got interactive ..."
+			#echo -n "$rlx_prompt";
+			rlx.prompt "username";
+			read username;
+			#echo "got username: $username";
+			#echo -n "$rlx_prompt";
+			rlx.prompt "password";
+			read -s password;
+			#echo "got password: $password";
+		fi
+	fi
+}
+
 function rlx {
 	# we need these executables so test early
 	executable.validate openssl curl tee;
+	
+	# the current host being used
+	local host="";
 	
 	# dependencies
 	require 'inet';
@@ -138,22 +199,25 @@ function rlx {
 	local host="ffsys.cloudant.com";
 	local protocol="http://";
 	
+	# https://ffsys.cloudant.com/rlx-world-writable/
+	
 	# TODO: only run this test when the host is not
 	# TODO: localhost or 127.0.0.1
 	
-	set +e;
-	# TODO: change this to use curl(1) for inet validation
-	inet.up? "$host";
-	if [ $? -gt 0 ]; then
-		console.quit 1 "could not connect to %s %s" "$host" "✘";
-	fi
-	set -e;
-
-	console.info "%s ok %s" "$host" "✓";
-	
+	# set +e;
+	# # TODO: change this to use curl(1) for inet validation
+	# inet.up? "$host";
+	# if [ $? -gt 0 ]; then
+	# 	console.quit 1 "could not connect to %s %s" "$host" "✘";
+	# fi
+	# set -e;
+	# 
+	# console.info "%s ok %s" "$host" "✓";
 	local cmd="${1:-}";
+	shift;
+	echo "got cmd: $cmd";
 	
-	#delegate "couchdb" "$cmd" "$@" || quit $? "task %s failed" "$func";
+	delegate "rlx" "$cmd" "$@" || quit $? "command %s failed" "$cmd";
 }
 
 rlx "$@";
