Update boilerplate search code in test executables.

diff --git a/test/bin/paths b/test/bin/paths
--- a/test/bin/paths
+++ b/test/bin/paths
@@ -1,10 +1,12 @@
-#! /usr/bin/env bash
+#!/usr/bin/env bash
 
 # test file for running executables
 # from various filesystems paths
 # relative, absolute, relative parent
 
-. ~/.strike/boilerplate.sh;
+boilerplate=$( command -v boilerplate.sh ) \
+  && . "$boilerplate" && unset boilerplate \
+  || { echo "fatal: could not locate boilerplate.sh" && exit 1; }
 boilerplate "$@";
 
 require.once assert;
diff --git a/test/bin/project/project b/test/bin/project/project
--- a/test/bin/project/project
+++ b/test/bin/project/project
@@ -1,12 +1,14 @@
-#! /usr/bin/env bash
+#!/usr/bin/env bash
 
-. ~/.strike/boilerplate.sh;
+boilerplate=$( command -v boilerplate.sh ) \
+  && . "$boilerplate" && unset boilerplate \
+  || { echo "fatal: could not locate boilerplate.sh" && exit 1; }
 boilerplate "$@";
 
 process.use strict;
 
-require.once 'assert';
-require.once 'tasks/project';
+require.once assert;
+require.once tasks/project;
 
 # let assert(3) know if this test
 # is being run standalone or as
diff --git a/test/bin/todo/todo b/test/bin/todo/todo
--- a/test/bin/todo/todo
+++ b/test/bin/todo/todo
@@ -1,13 +1,15 @@
-#! /usr/bin/env bash
+#!/usr/bin/env bash
 
-. ~/.strike/boilerplate.sh;
+boilerplate=$( command -v boilerplate.sh ) \
+  && . "$boilerplate" && unset boilerplate \
+  || { echo "fatal: could not locate boilerplate.sh" && exit 1; }
 boilerplate "$@";
 
 # switch on strict mode
 process.use strict;
 
-require 'assert';
-require 'tasks/todo';
+require assert;
+require tasks/todo;
 
 # let assert(3) know if this test
 # is being run standalone or as
