Replace leading tabs with spaces in all modules using the expand task and ensure all tests still pass.

diff --git a/lib/modules/core/console b/lib/modules/core/console
--- a/lib/modules/core/console
+++ b/lib/modules/core/console
@@ -1,183 +1,183 @@
 # main console entry point
 console() {
-	# list of available commands
-	local namespace="console";
-	local cmd="";
-	if [ $# -eq 0 ]; then
-		console quit 2 \
-			"no command specified";
-	fi
-	
-	if ! method.exists? "${namespace}${delegate_delimiter}${1}"; then
-		console quit 2 \
-			"invalid command %s" "${1}";
-	fi
-	
-	# exit code
-	local code=1;
-	cmd="$1";
-	shift;
-	
-	if [ "$cmd" == quit ] && [ $# -gt 0 ]; then
-		code="$1";
-		shift;
-	fi
-	
-	if [ -n "${cmd}" ]; then
-		if ! method.exists? "${namespace}.${cmd}"; then
-			console quit 2 "invalid command %s" "${cmd}";
-		fi
-		delegate "$namespace" "$cmd" "$@";
-	fi
+  # list of available commands
+  local namespace="console";
+  local cmd="";
+  if [ $# -eq 0 ]; then
+    console quit 2 \
+      "no command specified";
+  fi
+  
+  if ! method.exists? "${namespace}${delegate_delimiter}${1}"; then
+    console quit 2 \
+      "invalid command %s" "${1}";
+  fi
+  
+  # exit code
+  local code=1;
+  cmd="$1";
+  shift;
+  
+  if [ "$cmd" == quit ] && [ $# -gt 0 ]; then
+    code="$1";
+    shift;
+  fi
+  
+  if [ -n "${cmd}" ]; then
+    if ! method.exists? "${namespace}.${cmd}"; then
+      console quit 2 "invalid command %s" "${cmd}";
+    fi
+    delegate "$namespace" "$cmd" "$@";
+  fi
 }
 
 ## COMMANDS
 
 console.bell() {
-	printf "\a";
+  printf "\a";
 }
 
 # print the generic message header
 console.header() {
-	sprintf "$@" "${header}";
+  sprintf "$@" "${header}";
 }
 
 # print a header title
 console.title() {
-	sprintf --no-bright-prefix \
-		--prefix="${header_character:-}" "$@";
+  sprintf --no-bright-prefix \
+    --prefix="${header_character:-}" "$@";
 }
 
 # print a message with no prefix
 console.print() {
-	sprintf --no-prefix "$@";
+  sprintf --no-prefix "$@";
 }
 
 # print a prompt with no newline
 # and a space as the suffix
 console.prompt() {
-	sprintf --no-newline --readline \
-		--export=PS9 \
-		--suffix="${PS9_SUFFIX:-}" "$@";
+  sprintf --no-newline --readline \
+    --export=PS9 \
+    --suffix="${PS9_SUFFIX:-}" "$@";
 }
 
 # print a log message with a prefix
 console.log() {
-	local prefix=$( sprintf.block "${console_prefixes[log]}" );
-	sprintf --prefix="${prefix}" "$@";
+  local prefix=$( sprintf.block "${console_prefixes[log]}" );
+  sprintf --prefix="${prefix}" "$@";
 }
 
 # print an ok message with a prefix
 console.ok() {
-	local prefix=$( sprintf.block "${console_prefixes[ok]}" );
-	sprintf --suffix="${characters[tick]}" \
-		--prefix="${prefix}" "$@";
+  local prefix=$( sprintf.block "${console_prefixes[ok]}" );
+  sprintf --suffix="${characters[tick]}" \
+    --prefix="${prefix}" "$@";
 }
 
 # print an info message with a prefix
 console.info() {
-	local prefix=$( sprintf.block "${console_prefixes[info]}" );
-	sprintf --prefix="${prefix}" "$@";
+  local prefix=$( sprintf.block "${console_prefixes[info]}" );
+  sprintf --prefix="${prefix}" "$@";
 }
 
 ## ERROR COMMANDS
 
 # print a debug message to stderr
 console.debug() {
-	local prefix=$( sprintf.block "${console_prefixes[debug]}" );	
-	sprintf -2 --text=cyan --prefix="${prefix}" "$@";
+  local prefix=$( sprintf.block "${console_prefixes[debug]}" ); 
+  sprintf -2 --text=cyan --prefix="${prefix}" "$@";
 }
 
 # print a not ok message to stderr
 console.notok() {
-	local prefix=$( sprintf.block "${console_prefixes[notok]}" );
-	sprintf -2 --text=red --suffix="${characters[cross]}" \
-		--prefix="${prefix}" "$@";
+  local prefix=$( sprintf.block "${console_prefixes[notok]}" );
+  sprintf -2 --text=red --suffix="${characters[cross]}" \
+    --prefix="${prefix}" "$@";
 }
 
 # print an error message to stderr
 console.error() {
-	local prefix=$( sprintf.block "${console_prefixes[error]}" );
-	sprintf -2 --text=red --prefix="${prefix}" "$@";
+  local prefix=$( sprintf.block "${console_prefixes[error]}" );
+  sprintf -2 --text=red --prefix="${prefix}" "$@";
 }
 
 # print a warning message to stderr
 console.warn() {
-	local prefix=$( sprintf.block "${console_prefixes[warn]}" );
-	sprintf -2 --text=magenta --prefix="${prefix}" "$@";
+  local prefix=$( sprintf.block "${console_prefixes[warn]}" );
+  sprintf -2 --text=magenta --prefix="${prefix}" "$@";
 }
 
 # throw a stack trace with
 # preceeding error message
 console.throw() {
-	local message="${1:-Unknown error}";
-	console error "$message";
-	console trace 1;
+  local message="${1:-Unknown error}";
+  console error "$message";
+  console trace 1;
 }
 
 # print a stack trace as a series of error messages
 console.trace() {
-	local prefix=$( sprintf.block "${console_prefixes[trace]}" );
-	local offset="${1:-0}";
-	local frame="$offset";
-	local line;
-	local data=( $( caller $frame ) );
-	while [ "${#data[@]}" -gt 0 ]; do
-		
-		# occassionally the line number is reported with a leading hyphen???
-		line="${data[0]#-}";
-		#echo "got data: ${data[@]}";
-		
-		sprintf -2 --text=red --prefix="${prefix}" \
-			"%s:%s %s" "${data[2]}" "$line" "${data[1]}";
-		: $((frame++));
-		data=( $( caller $frame ) );
-	done
+  local prefix=$( sprintf.block "${console_prefixes[trace]}" );
+  local offset="${1:-0}";
+  local frame="$offset";
+  local line;
+  local data=( $( caller $frame ) );
+  while [ "${#data[@]}" -gt 0 ]; do
+    
+    # occassionally the line number is reported with a leading hyphen???
+    line="${data[0]#-}";
+    #echo "got data: ${data[@]}";
+    
+    sprintf -2 --text=red --prefix="${prefix}" \
+      "%s:%s %s" "${data[2]}" "$line" "${data[1]}";
+    : $((frame++));
+    data=( $( caller $frame ) );
+  done
 }
 
 # exit with a failure
 console.quit() {
-	if [ $# -gt 0 ]; then
-		console notok "$@";
-	fi
-	exit ${code:-1};
+  if [ $# -gt 0 ]; then
+    console notok "$@";
+  fi
+  exit ${code:-1};
 }
 
 # exit successfully
 console.success() {
-	if [ $# -gt 0 ]; then
-		console ok "$@";
-	fi
-	exit 0;
+  if [ $# -gt 0 ]; then
+    console ok "$@";
+  fi
+  exit 0;
 }
 
 # mark functions as read only
 readonly -f console \
-	console.header \
-	console.title \
-	console.print \
-	console.log \
-	console.ok \
-	console.info \
-	console.debug \
-	console.warn \
-	console.notok \
-	console.error \
-	console.throw \
-	console.trace \
-	console.quit \
-	console.success;
+  console.header \
+  console.title \
+  console.print \
+  console.log \
+  console.ok \
+  console.info \
+  console.debug \
+  console.warn \
+  console.notok \
+  console.error \
+  console.throw \
+  console.trace \
+  console.quit \
+  console.success;
 
 # redirect stderr to console error
 # so that all error messages are highlighted
 # wherever possible
 # NOTE: this must be done before setting noclobber
 # console.shell.error() {
-# 	if [ -t 2 ]; then
-# 		echo -e "\033[1;31m$line\033[0m";
-# 	else
-# 		echo "$line";
-# 	fi
+#   if [ -t 2 ]; then
+#     echo -e "\033[1;31m$line\033[0m";
+#   else
+#     echo "$line";
+#   fi
 # }
 
 # exec 2> >( while read line; do console.shell.error >&2; done);
@@ -193,7 +193,7 @@ readonly -f console \
 # mask the info system executable
 # legacy due to the old info command declaration
 info() {
-	console info "$@";
+  console info "$@";
 }
 
 # alias "info=console info";
diff --git a/lib/modules/core/fs b/lib/modules/core/fs
--- a/lib/modules/core/fs
+++ b/lib/modules/core/fs
@@ -1,110 +1,110 @@
 ######################################################################
-#	Expands a path to an absolute representation of an existing
-#	directory.
+# Expands a path to an absolute representation of an existing
+# directory.
 #
-#	$1 		The path to the directory.
+# $1    The path to the directory.
 ######################################################################
 fs.path.expand() {
-	local dir="${1:-}";
-	if [  -d "$dir" ]; then
-		local owd=`pwd`;
-		cd "$dir" > /dev/null;
-		_result=`pwd`;
-		cd "$owd" > /dev/null;
-	elif [ ! -d "$dir" ]; then
-		local nm=`basename $dir`
-		dir=`dirname $dir`;
-		fs.path.expand "$dir";
-		_result="$_result/$nm";
-	fi
-	if [ ! -e "$dir" -o ! -e "$_result" ]; then
-		console error "unable to expand path %s" "$dir";
-		_result="$1";
-	fi
+  local dir="${1:-}";
+  if [  -d "$dir" ]; then
+    local owd=`pwd`;
+    cd "$dir" > /dev/null;
+    _result=`pwd`;
+    cd "$owd" > /dev/null;
+  elif [ ! -d "$dir" ]; then
+    local nm=`basename $dir`
+    dir=`dirname $dir`;
+    fs.path.expand "$dir";
+    _result="$_result/$nm";
+  fi
+  if [ ! -e "$dir" -o ! -e "$_result" ]; then
+    console error "unable to expand path %s" "$dir";
+    _result="$1";
+  fi
 }
 
 # escapes leading dash characters
 # fs.path.dash.escape() {
-# 	_result="${1:-}";
-# 	if [[ "${1:-}" =~ ^-+ ]]; then
-# 		local re="^-(.*)";
-# 		while [[ "$_result" =~ $re ]];
-# 			do
-# 				_result="\-${BASH_REMATCH[1]}";
-# 		done
-# 	fi
+#   _result="${1:-}";
+#   if [[ "${1:-}" =~ ^-+ ]]; then
+#     local re="^-(.*)";
+#     while [[ "$_result" =~ $re ]];
+#       do
+#         _result="\-${BASH_REMATCH[1]}";
+#     done
+#   fi
 # }
 
 # retrieve a dirname and assign the result to a variable ($2)
 fs.dirname() {
-	local path="${1:-}";
-	local varname="${2:-_result}";
-	local stripdot="${3:-false}";
-	local result=$( dirname -- "${path}" );
-	if $stripdot && [ "${result}" == "." ]; then
-		result="";
-	fi
-	eval "$varname=\"$result\"";
+  local path="${1:-}";
+  local varname="${2:-_result}";
+  local stripdot="${3:-false}";
+  local result=$( dirname -- "${path}" );
+  if $stripdot && [ "${result}" == "." ]; then
+    result="";
+  fi
+  eval "$varname=\"$result\"";
 }
 
 # retrieve a basename, and assign the result to a variable ($2)
 fs.basename() {
-	local path="${1:-}";
-	local varname="${2:-_result}";
-	local stripdot="${3:-false}";
-	local result=$( basename -- "${path}" );
-	if $stripdot && [ "${result}" == "." ]; then
-		result="";
-	fi
-	eval "$varname=\"$result\"";
+  local path="${1:-}";
+  local varname="${2:-_result}";
+  local stripdot="${3:-false}";
+  local result=$( basename -- "${path}" );
+  if $stripdot && [ "${result}" == "." ]; then
+    result="";
+  fi
+  eval "$varname=\"$result\"";
 }
 
 # walks the parent hierarchy looking for a file
 fs.walk() {
-	local name="${1:-}";
-	local flag="${2:-"-f"}";
-	local dir="$PWD";
-	local file="${dir}/${name}";
-	while ! test "$flag" "$file" && [ "$dir" != "/" ];
-		do
-			dir=$( dirname "$dir" );
-			file="${dir}/${name}";
-	done
-	if test "$flag" "$file"; then
-		_result="$file";
-	else
-		_result="";
-	fi
+  local name="${1:-}";
+  local flag="${2:-"-f"}";
+  local dir="$PWD";
+  local file="${dir}/${name}";
+  while ! test "$flag" "$file" && [ "$dir" != "/" ];
+    do
+      dir=$( dirname "$dir" );
+      file="${dir}/${name}";
+  done
+  if test "$flag" "$file"; then
+    _result="$file";
+  else
+    _result="";
+  fi
 }
 
 ######################################################################
-#	Finds symbolic links that point to themselves and will cause cp
-#	to fail.
+# Finds symbolic links that point to themselves and will cause cp
+# to fail.
 #
-#	$1 		The path to the directory to search.
+# $1    The path to the directory to search.
 ######################################################################
 # function find_recursive_symlinks {
-# 	local src="$1";
-# 	local links=( $(find "$src" -type l) );
-# 	local l;
-# 	local n;
-# 	local t;
-# 	local output=();
-# 	if [ ${#links[@]} -gt 0 ]; then
-# 		for l in ${links[@]}
-# 			do
-# 				t=`readlink "$l"`;
-# 				n=`basename $l`;
-# 				#ensure we always compare case-insensitive
-# 				n=`echo "$n" | tr '[:upper:]' '[:lower:]'`;
-# 				t=`echo "$t" | tr '[:upper:]' '[:lower:]'`;
-# 				if [ "$n" == "$t" ]; then
-# 					#echo "recursive $l : $n : $t";
-# 					output+=( "$l" );
-# 				fi
-# 		done
-# 	fi
-# 	_result="${output[@]:+${output[@]}}";
+#   local src="$1";
+#   local links=( $(find "$src" -type l) );
+#   local l;
+#   local n;
+#   local t;
+#   local output=();
+#   if [ ${#links[@]} -gt 0 ]; then
+#     for l in ${links[@]}
+#       do
+#         t=`readlink "$l"`;
+#         n=`basename $l`;
+#         #ensure we always compare case-insensitive
+#         n=`echo "$n" | tr '[:upper:]' '[:lower:]'`;
+#         t=`echo "$t" | tr '[:upper:]' '[:lower:]'`;
+#         if [ "$n" == "$t" ]; then
+#           #echo "recursive $l : $n : $t";
+#           output+=( "$l" );
+#         fi
+#     done
+#   fi
+#   _result="${output[@]:+${output[@]}}";
 # }
 
 # WARNING: these aliases will be removed in a future version
diff --git a/lib/modules/tasks/compress b/lib/modules/tasks/compress
--- a/lib/modules/tasks/compress
+++ b/lib/modules/tasks/compress
@@ -8,104 +8,104 @@ require.once help;
 help.man.page "compress" "task-compress.7";
 
 tasks.compress.initialize() {
-	executable.validate gzip gunzip;
+  executable.validate gzip gunzip;
 }
 
 
 taskinfo compress "Utility for compressing multiple files, useful for creating compressed assets for web applications prior to deployment";
 tasks.compress() {
-	
-	# the extension for compressed files
-	local compress_extension="gz";
-	
-	# whether we recurse into sub-directories
-	local compress_recursive=false;	
+  
+  # the extension for compressed files
+  local compress_extension="gz";
+  
+  # whether we recurse into sub-directories
+  local compress_recursive=false; 
 
-	# whether we delete files,
-	# the default is to keep files
-	local compress_delete=false;
-	
-	# debug commands as they are executed
-	local compress_debug=false;
-	
-	# verbose output
-	local compress_verbose=false;
-	
-	# noop
-	local compress_noop=false;
-	
-	# include patterns
-	local compress_include_patterns=();
-	
-	# exclude patterns
-	local compress_exclude_patterns=();
-	
-	# internal variable for recursion
-	local compress_depth=-1;
-	
-	# an output directory when deflating/extracting
-	local compress_output="";
-	
-	# a base directory to use in conjunction
-	# with the --output and --recursive options
-	# so that output hierarchies can match
-	# input hierarchies
-	local compress_dir="";
-	
-	# map of options to command names
-	declare -A commands;
-	commands=(
-		[-c]="deflate"
-		[-x]="inflate"
-		[create]="deflate"
-		[extract]="inflate"
-	);
-	
-	# do command procesing via delegation
-	if [ $# -gt 0 ]; then
-		local cmd="${1:-}";
-		local cmdmethod="${commands[$cmd]:-}";
-		if [ -z "$cmdmethod" ]; then
-			console quit 1 "invalid compress command %s" "$1";
-		fi
+  # whether we delete files,
+  # the default is to keep files
+  local compress_delete=false;
+  
+  # debug commands as they are executed
+  local compress_debug=false;
+  
+  # verbose output
+  local compress_verbose=false;
+  
+  # noop
+  local compress_noop=false;
+  
+  # include patterns
+  local compress_include_patterns=();
+  
+  # exclude patterns
+  local compress_exclude_patterns=();
+  
+  # internal variable for recursion
+  local compress_depth=-1;
+  
+  # an output directory when deflating/extracting
+  local compress_output="";
+  
+  # a base directory to use in conjunction
+  # with the --output and --recursive options
+  # so that output hierarchies can match
+  # input hierarchies
+  local compress_dir="";
+  
+  # map of options to command names
+  declare -A commands;
+  commands=(
+    [-c]="deflate"
+    [-x]="inflate"
+    [create]="deflate"
+    [extract]="inflate"
+  );
+  
+  # do command procesing via delegation
+  if [ $# -gt 0 ]; then
+    local cmd="${1:-}";
+    local cmdmethod="${commands[$cmd]:-}";
+    if [ -z "$cmdmethod" ]; then
+      console quit 1 "invalid compress command %s" "$1";
+    fi
 
-		# remove the command option
-		shift;
-		
-		# parse remaining options
-		__compress.parse "$@";
-		local opts=( $_result );
-		delegate "cmp.${FUNCNAME}" "$cmdmethod" "${opts[@]:-}";
-	else
-		console quit 1 "no compress command specified";
-	fi
+    # remove the command option
+    shift;
+    
+    # parse remaining options
+    __compress.parse "$@";
+    local opts=( $_result );
+    delegate "cmp.${FUNCNAME}" "$cmdmethod" "${opts[@]:-}";
+  else
+    console quit 1 "no compress command specified";
+  fi
 }
 
 function cmp.tasks.compress.inflate {
-	if [ $# -eq 0 ]; then
-		__compress.missing.files;
-	fi
-	if ! $compress_noop; then
-		__compress.files.get "__compress.inflate" false "$@";
-	else
-		__compress.files.get "__compress.print" false "$@";
-	fi
+  if [ $# -eq 0 ]; then
+    __compress.missing.files;
+  fi
+  if ! $compress_noop; then
+    __compress.files.get "__compress.inflate" false "$@";
+  else
+    __compress.files.get "__compress.print" false "$@";
+  fi
 }
 
 function cmp.tasks.compress.deflate {
-	if [ $# -eq 0 ]; then
-		__compress.missing.files;
-	fi
-	if ! $compress_noop; then
-		__compress.files.get "__compress.deflate" true "$@";
-	else
-		__compress.files.get "__compress.print" true "$@";
-	fi
+  if [ $# -eq 0 ]; then
+    __compress.missing.files;
+  fi
+  if ! $compress_noop; then
+    __compress.files.get "__compress.deflate" true "$@";
+  else
+    __compress.files.get "__compress.print" true "$@";
+  fi
 }
 
 ######################################################################
 #
-#	PRIVATE METHODS
+# PRIVATE METHODS
 #
 ######################################################################
 
@@ -113,284 +113,284 @@ function cmp.tasks.compress.deflate {
 # and invokes a callback function for each
 # file being processed
 function __compress.files.get {
-	local callback="${1:-}";
-	shift;
-	local skip="${1:-true}";
-	shift;
-	local files=( "$@" );
-	if [ -n "$callback" ]; then
-		: $((compress_depth++));
-		if [ "${1:-}" == "-" ]; then
-			shift;
-			unset files[0];
-			if [ ! -t 0 ]; then
-				while IFS= read -r line
-					do
-						files+=( "$line" );
-				done
-			fi
-		fi
-		
-		if [ ${#files[@]} -eq 0 ]; then
-			console quit 1 "no files specified";
-		fi
-		
-		local file;
-		for file in "${files[@]}"
-			do
-				local target_files=();
-				if [ -d "$file" ]; then
-					if ! $compress_recursive && [ $compress_depth -eq 0 ]; then
-						#__compress.files.get "$callback" "$skip" $( find "$file" -depth 1 -type f );
-						
-						# local findopts=( "-O1" "$file" "-type" "f" );
-						# if [[ "$OSTYPE" =~ ^darwin ]]; then
-						# 	findopts=( "$file" "-depth" "1" "-type" "f" );
-						# fi
-						# target_files=( $( find "${fileopts[@]}" ) );
-						
-						local nf;
-						for nf in "${file}"/*
-							do
-								target_files+=( "$nf" );
-						done
-						
-					elif $compress_recursive; then
-						#__compress.files.get "$callback" "$skip" $( find "$file" -type f );
-						target_files=( $( find "$file" -type f ) );
-					fi
-					__compress.files.get "$callback" "$skip" "${target_files[@]:-}";
-					continue;
-				fi
-				
-				# ignore .gz files when compressing
-				if $skip && [[ "$file" =~ \.gz$ ]]; then
-					continue;
-				# ignore anything but .gz files when extracting
-				elif ! $skip && [[ ! "$file" =~ \.gz$ ]]; then
-					continue;
-				fi
-				
-				if [ ! -e "$file" ]; then
-					console warn "skipping non-existent file %s" "$file";
-					continue;
-				fi
-				
-				# check patterns
-				if ! __compress.files.include? "$file"; then
-					continue;
-				fi
-				
-				if [ ! -f "$file" ]; then
-					console quit 1 "invalid file %s" "$f";
-				fi
-				
-				"$callback";
-		done
-	fi
+  local callback="${1:-}";
+  shift;
+  local skip="${1:-true}";
+  shift;
+  local files=( "$@" );
+  if [ -n "$callback" ]; then
+    : $((compress_depth++));
+    if [ "${1:-}" == "-" ]; then
+      shift;
+      unset files[0];
+      if [ ! -t 0 ]; then
+        while IFS= read -r line
+          do
+            files+=( "$line" );
+        done
+      fi
+    fi
+    
+    if [ ${#files[@]} -eq 0 ]; then
+      console quit 1 "no files specified";
+    fi
+    
+    local file;
+    for file in "${files[@]}"
+      do
+        local target_files=();
+        if [ -d "$file" ]; then
+          if ! $compress_recursive && [ $compress_depth -eq 0 ]; then
+            #__compress.files.get "$callback" "$skip" $( find "$file" -depth 1 -type f );
+            
+            # local findopts=( "-O1" "$file" "-type" "f" );
+            # if [[ "$OSTYPE" =~ ^darwin ]]; then
+            #   findopts=( "$file" "-depth" "1" "-type" "f" );
+            # fi
+            # target_files=( $( find "${fileopts[@]}" ) );
+            
+            local nf;
+            for nf in "${file}"/*
+              do
+                target_files+=( "$nf" );
+            done
+            
+          elif $compress_recursive; then
+            #__compress.files.get "$callback" "$skip" $( find "$file" -type f );
+            target_files=( $( find "$file" -type f ) );
+          fi
+          __compress.files.get "$callback" "$skip" "${target_files[@]:-}";
+          continue;
+        fi
+        
+        # ignore .gz files when compressing
+        if $skip && [[ "$file" =~ \.gz$ ]]; then
+          continue;
+        # ignore anything but .gz files when extracting
+        elif ! $skip && [[ ! "$file" =~ \.gz$ ]]; then
+          continue;
+        fi
+        
+        if [ ! -e "$file" ]; then
+          console warn "skipping non-existent file %s" "$file";
+          continue;
+        fi
+        
+        # check patterns
+        if ! __compress.files.include? "$file"; then
+          continue;
+        fi
+        
+        if [ ! -f "$file" ]; then
+          console quit 1 "invalid file %s" "$f";
+        fi
+        
+        "$callback";
+    done
+  fi
 }
 
 function __compress.files.include? {
-	local file="${1:-}";
-	local ptn name;
-	fs.basename "$file" "name";
-	if [ ${#compress_exclude_patterns[@]} -gt 0 ]; then
-		for ptn in ${compress_exclude_patterns[@]}
-			do
-				# matches an exclude pattern
-				[[ "$name" =~ $ptn ]] && { return 1; }
-				if [ $? -eq 2 ]; then __compress.invalid.pattern; fi
-		done
-	fi
-	
-	if [ ${#compress_include_patterns[@]} -gt 0 ]; then
-		for ptn in ${compress_include_patterns[@]}
-			do
-				# matches an include pattern
-				[[ "$name" =~ $ptn ]] && { return 0; }
-				if [ $? -eq 2 ]; then __compress.invalid.pattern; fi
-		done
-	fi
-	
-	# got some include patterns and matching failed
-	# we don't include it
-	if [ ${#compress_include_patterns[@]} -gt 0 ]; then
-		return 1;
-	fi
-	
-	# include by default
-	return 0;
+  local file="${1:-}";
+  local ptn name;
+  fs.basename "$file" "name";
+  if [ ${#compress_exclude_patterns[@]} -gt 0 ]; then
+    for ptn in ${compress_exclude_patterns[@]}
+      do
+        # matches an exclude pattern
+        [[ "$name" =~ $ptn ]] && { return 1; }
+        if [ $? -eq 2 ]; then __compress.invalid.pattern; fi
+    done
+  fi
+  
+  if [ ${#compress_include_patterns[@]} -gt 0 ]; then
+    for ptn in ${compress_include_patterns[@]}
+      do
+        # matches an include pattern
+        [[ "$name" =~ $ptn ]] && { return 0; }
+        if [ $? -eq 2 ]; then __compress.invalid.pattern; fi
+    done
+  fi
+  
+  # got some include patterns and matching failed
+  # we don't include it
+  if [ ${#compress_include_patterns[@]} -gt 0 ]; then
+    return 1;
+  fi
+  
+  # include by default
+  return 0;
 }
 
 function __compress.deflate {
-	local out="${file}.${compress_extension}";
-	local nm name compress_options results status;
-	fs.basename "$file" "nm";	
-	fs.basename "$out" "name";
-	__compress.output;	
-	compress_options=( -c --best --force -v "$file" );
-	if $compress_debug; then
-		console info "${executables[gzip]} %s 1>| %s" "${compress_options[*]}" "$out";
-	fi
-	results=( $( { "${executables[gzip]}" "${compress_options[@]}" 1>| "$out"; } 2>&1 ) );
-	status=$?;	
-	if $compress_delete && [ $status -eq 0 ]; then
-		rm "$file" || quit 1 "could not delete %s" "$file";
-	fi
-	if [ $status -gt 0 ]; then
-		console quit 1 "failed to compress %s" "$file";
-	fi
-	if $compress_verbose; then
-		console info "%s > %s (%s)" "$nm" "$name" "${results[${#results[@]}-1]}";
-	fi
-	# also touch the file to set modification time
-	# in case it already exists
-	if [ -f "$out" ]; then
-		touch "$out";
-	fi
+  local out="${file}.${compress_extension}";
+  local nm name compress_options results status;
+  fs.basename "$file" "nm"; 
+  fs.basename "$out" "name";
+  __compress.output;  
+  compress_options=( -c --best --force -v "$file" );
+  if $compress_debug; then
+    console info "${executables[gzip]} %s 1>| %s" "${compress_options[*]}" "$out";
+  fi
+  results=( $( { "${executables[gzip]}" "${compress_options[@]}" 1>| "$out"; } 2>&1 ) );
+  status=$?;  
+  if $compress_delete && [ $status -eq 0 ]; then
+    rm "$file" || quit 1 "could not delete %s" "$file";
+  fi
+  if [ $status -gt 0 ]; then
+    console quit 1 "failed to compress %s" "$file";
+  fi
+  if $compress_verbose; then
+    console info "%s > %s (%s)" "$nm" "$name" "${results[${#results[@]}-1]}";
+  fi
+  # also touch the file to set modification time
+  # in case it already exists
+  if [ -f "$out" ]; then
+    touch "$out";
+  fi
 }
 
-function __compress.inflate {	
-	local out="${file%.gz}";
-	local nm name compress_options results;
-	fs.basename "$file" "nm";
-	fs.basename "$out" "name";
-	__compress.output;
-	compress_options=( -c -v "$file" );
-	
-	if $compress_debug; then
-		console info "${executables[gunzip]} %s 1>| %s" "${compress_options[*]}" "$out";
-	fi
-	
-	results=( $( { "${executables[gunzip]}" "${compress_options[@]}" 1>| "$out"; } 2>&1 ) );
-	status=$?;
-	if $compress_delete && [ $status -eq 0 ]; then
-		rm "$file" || quit 1 "could not delete %s" "$file";
-	fi
-	if [ $status -gt 0 ]; then
-		console quit 1 "failed to extract %s" "$file";
-	fi
-	if $compress_verbose; then
-		console info "%s < %s (%s)" "$name" "$nm" "${results[${#results[@]}-1]}";
-	fi
-	# also touch the file to set modification time
-	# in case it already exists
-	if [ -f "$out" ]; then	
-		touch "$out";
-	fi
+function __compress.inflate { 
+  local out="${file%.gz}";
+  local nm name compress_options results;
+  fs.basename "$file" "nm";
+  fs.basename "$out" "name";
+  __compress.output;
+  compress_options=( -c -v "$file" );
+  
+  if $compress_debug; then
+    console info "${executables[gunzip]} %s 1>| %s" "${compress_options[*]}" "$out";
+  fi
+  
+  results=( $( { "${executables[gunzip]}" "${compress_options[@]}" 1>| "$out"; } 2>&1 ) );
+  status=$?;
+  if $compress_delete && [ $status -eq 0 ]; then
+    rm "$file" || quit 1 "could not delete %s" "$file";
+  fi
+  if [ $status -gt 0 ]; then
+    console quit 1 "failed to extract %s" "$file";
+  fi
+  if $compress_verbose; then
+    console info "%s < %s (%s)" "$name" "$nm" "${results[${#results[@]}-1]}";
+  fi
+  # also touch the file to set modification time
+  # in case it already exists
+  if [ -f "$out" ]; then  
+    touch "$out";
+  fi
 }
 
 # print file information
 function __compress.print {
-	local size="";
-	if $compress_verbose && [ -f "$file" ]; then
-		size=( $( du -h "$file" ) );
-		size=" ${size[0]}";
-	fi
-	console print "${file}%s" "$size";
+  local size="";
+  if $compress_verbose && [ -f "$file" ]; then
+    size=( $( du -h "$file" ) );
+    size=" ${size[0]}";
+  fi
+  console print "${file}%s" "$size";
 }
 
 # massage $out depending upon the --output and --dir options
 function __compress.output {
-	if [ -n "$compress_output" ]; then
-		if [ -n "$compress_dir" ]; then
-			local parent;
-			fs.dirname "$out" "parent";
-			local relative="${parent#$compress_dir}";
-			if [ "$relative" == "$out" ]; then
-				console warn "output file %s is not relative to %s" "$out" "$compress_dir";
-			fi
-			relative="${relative#/}";
-			relative="${compress_output}/${relative}";
-			relative="${relative%/}";			
-			if [ ! -d "$relative" ]; then
-				mkdir -p "$relative";
-			fi
-			out="${relative}/${name}";
-		else
-			out="${compress_output}/$name";
-		fi
-	fi
+  if [ -n "$compress_output" ]; then
+    if [ -n "$compress_dir" ]; then
+      local parent;
+      fs.dirname "$out" "parent";
+      local relative="${parent#$compress_dir}";
+      if [ "$relative" == "$out" ]; then
+        console warn "output file %s is not relative to %s" "$out" "$compress_dir";
+      fi
+      relative="${relative#/}";
+      relative="${compress_output}/${relative}";
+      relative="${relative%/}";     
+      if [ ! -d "$relative" ]; then
+        mkdir -p "$relative";
+      fi
+      out="${relative}/${name}";
+    else
+      out="${compress_output}/$name";
+    fi
+  fi
 }
 
 # parse command line options
 function __compress.parse {
-	# unprocessed options
-	local options=();
-	
-	local value;
-	# handle other options
-	while [ "${1:-}" != "" ]; do
-		case $1 in
-			--delete )
-				compress_delete=true;
-				;;
-			-r | --recursive )
-				compress_recursive=true;
-				;;
-			--debug )
-				compress_debug=true;
-				;;				
-			-v | --verbose )
-				compress_verbose=true;
-				;;
-			-i | --include )
-				shift;
-				compress_include_patterns+=( "${1:-}" );
-				;;
-			-e | --exclude )
-				shift;
-				compress_exclude_patterns+=( "${1:-}" );
-				;;
-			-d | --dir )
-				shift;
-				value="${1:-}";
-				if [ -z "$value" ]; then
-					console quit 1 "no directory specified for the %s option" "-d | --dir";
-				fi
-				if [ ! -d "$value" ]; then
-					console quit 1 "%s not a directory" "$value";
-				fi
-				if [ ! -w "$value" ]; then
-					console quit 1 "%s not writable" "$value";
-				fi
-				compress_dir="$value";
-				;;
-			-o | --output )
-				shift;
-				value="${1:-}";
-				if [ -z "$value" ]; then
-					console quit 1 "no directory specified for the %s option" "-o | --output";
-				fi
-				if [ ! -d "$value" ] || [ ! -w "$value" ]; then
-					console quit 1 "invalid output directory %s" "$value";
-				fi
-				# remove any trailing slash
-				value="${value%/}";
-				compress_output="$value";
-				;;
-			--noop )
-				compress_noop=true;
-				;;							
-			* )
-				options+=( "$1" );
-				;;
-		esac
-		if [ $# -ne 0 ]; then
-			shift;
-		else
-			break;
-		fi
-	done
+  # unprocessed options
+  local options=();
+  
+  local value;
+  # handle other options
+  while [ "${1:-}" != "" ]; do
+    case $1 in
+      --delete )
+        compress_delete=true;
+        ;;
+      -r | --recursive )
+        compress_recursive=true;
+        ;;
+      --debug )
+        compress_debug=true;
+        ;;        
+      -v | --verbose )
+        compress_verbose=true;
+        ;;
+      -i | --include )
+        shift;
+        compress_include_patterns+=( "${1:-}" );
+        ;;
+      -e | --exclude )
+        shift;
+        compress_exclude_patterns+=( "${1:-}" );
+        ;;
+      -d | --dir )
+        shift;
+        value="${1:-}";
+        if [ -z "$value" ]; then
+          console quit 1 "no directory specified for the %s option" "-d | --dir";
+        fi
+        if [ ! -d "$value" ]; then
+          console quit 1 "%s not a directory" "$value";
+        fi
+        if [ ! -w "$value" ]; then
+          console quit 1 "%s not writable" "$value";
+        fi
+        compress_dir="$value";
+        ;;
+      -o | --output )
+        shift;
+        value="${1:-}";
+        if [ -z "$value" ]; then
+          console quit 1 "no directory specified for the %s option" "-o | --output";
+        fi
+        if [ ! -d "$value" ] || [ ! -w "$value" ]; then
+          console quit 1 "invalid output directory %s" "$value";
+        fi
+        # remove any trailing slash
+        value="${value%/}";
+        compress_output="$value";
+        ;;
+      --noop )
+        compress_noop=true;
+        ;;              
+      * )
+        options+=( "$1" );
+        ;;
+    esac
+    if [ $# -ne 0 ]; then
+      shift;
+    else
+      break;
+    fi
+  done
 
-	# return remaining options back
-	_result="${options[@]:-}";
+  # return remaining options back
+  _result="${options[@]:-}";
 }
 
 function __compress.invalid.pattern {
-	console quit 2 "invalid pattern %s" "$ptn";
+  console quit 2 "invalid pattern %s" "$ptn";
 }
 
 function __compress.missing.files {
-	console quit 1 "no files specified";
+  console quit 1 "no files specified";
 }
diff --git a/lib/modules/tasks/latex b/lib/modules/tasks/latex
--- a/lib/modules/tasks/latex
+++ b/lib/modules/tasks/latex
@@ -39,273 +39,273 @@
 
 taskinfo latex "Compile latex source to pdf or dvi"
 tasks.latex() {
-	executable.validate pdflatex;
-	
-	# default directory used to search for files
-	local latex_dir="./doc/latex";
-	
-	# default output format
-	local latex_output_format="pdf";
-	
-	# options passed to pdflatex(1)
-	local latex_options=();
-	
-	# list of source files
-	local latex_files=();
-	
-	# the output directory for compilation
-	local latex_output="";
-	
-	# whether we are debugging the commands
-	# being executed
-	local latex_debug=false;
-	
-	# do command procesing via delegation
-	if [ $# -gt 0 ]; then
-		local cmd="${1:-}";
+  executable.validate pdflatex;
+  
+  # default directory used to search for files
+  local latex_dir="./doc/latex";
+  
+  # default output format
+  local latex_output_format="pdf";
+  
+  # options passed to pdflatex(1)
+  local latex_options=();
+  
+  # list of source files
+  local latex_files=();
+  
+  # the output directory for compilation
+  local latex_output="";
+  
+  # whether we are debugging the commands
+  # being executed
+  local latex_debug=false;
+  
+  # do command procesing via delegation
+  if [ $# -gt 0 ]; then
+    local cmd="${1:-}";
 
-		if [ "$cmd" == "pdf" ] || [ "$cmd" == "dvi" ]; then
-			# remove the command option
-			shift;
-			latex_output_format="$cmd";
-		fi
-		
-		# parse remaining options
-		__latex.parse "$@";
-		local opts=( $_result );
-		__latex.defaults;
-		delegate "ltx.${FUNCNAME}" "compile" "${opts[@]:-}";
-	else
-		__latex.defaults;
-		ltx.tasks.latex.all;
-	fi
+    if [ "$cmd" == "pdf" ] || [ "$cmd" == "dvi" ]; then
+      # remove the command option
+      shift;
+      latex_output_format="$cmd";
+    fi
+    
+    # parse remaining options
+    __latex.parse "$@";
+    local opts=( $_result );
+    __latex.defaults;
+    delegate "ltx.${FUNCNAME}" "compile" "${opts[@]:-}";
+  else
+    __latex.defaults;
+    ltx.tasks.latex.all;
+  fi
 }
 
 function ltx.tasks.latex.compile {
-	if [ -z "$1" ]; then
-		shift;
-	fi
-	# just the output format specified
-	# pass on to the all behaviour
-	if [ $# -eq 0 ]; then
-		ltx.tasks.latex.all;
-	else
-		__latex.compile;
-	fi
+  if [ -z "$1" ]; then
+    shift;
+  fi
+  # just the output format specified
+  # pass on to the all behaviour
+  if [ $# -eq 0 ]; then
+    ltx.tasks.latex.all;
+  else
+    __latex.compile;
+  fi
 }
 
 # compile everything we find in doc/latex
 # to ${target}
 function ltx.tasks.latex.all {
-	__latex.files.get;
-	if [ ${#latex_files[@]} -eq 0 ]; then
-		console quit 1 "no %s files in %s" ".tex" "$latex_dir";
-	else
-		__latex.compile.all;
-	fi
+  __latex.files.get;
+  if [ ${#latex_files[@]} -eq 0 ]; then
+    console quit 1 "no %s files in %s" ".tex" "$latex_dir";
+  else
+    __latex.compile.all;
+  fi
 }
 
 ######################################################################
 #
-#	PRIVATE METHODS
+# PRIVATE METHODS
 #
 ######################################################################
 
 # configures default options
 function __latex.defaults {
-	if [ -z "$latex_output" ]; then
-		latex_output="${target}/$latex_output_format";
-	fi
-	if [ ! -d "$latex_output" ]; then
-		mkdir -p "$latex_output" || quit 1 "could not create latex output directory %s" "$latex_output";
-	fi
-	
-	# always expand path so that nested directory
-	# structure are correct when using the ./doc/latex path
-	if [ -d "$latex_output" ]; then
-		fs.path.expand "$latex_output";
-		latex_output="$_result";
-	fi
-	
-	#  -output-directory should always be index 0
-	latex_options+=( "-output-directory=$latex_output" );
-	
-	latex_options+=( "-output-format=$latex_output_format" );
-	latex_options+=( "-halt-on-error" );
-	
-	# TODO: add custom latex options here
+  if [ -z "$latex_output" ]; then
+    latex_output="${target}/$latex_output_format";
+  fi
+  if [ ! -d "$latex_output" ]; then
+    mkdir -p "$latex_output" || quit 1 "could not create latex output directory %s" "$latex_output";
+  fi
+  
+  # always expand path so that nested directory
+  # structure are correct when using the ./doc/latex path
+  if [ -d "$latex_output" ]; then
+    fs.path.expand "$latex_output";
+    latex_output="$_result";
+  fi
+  
+  #  -output-directory should always be index 0
+  latex_options+=( "-output-directory=$latex_output" );
+  
+  latex_options+=( "-output-format=$latex_output_format" );
+  latex_options+=( "-halt-on-error" );
+  
+  # TODO: add custom latex options here
 }
 
 function __latex.files.get {
-	local dir="${1:-$latex_dir}";
-	if [ -d "$dir" ]; then
-		latex_files+=( $( find "$dir" -name *.tex ) );
-	fi
+  local dir="${1:-$latex_dir}";
+  if [ -d "$dir" ]; then
+    latex_files+=( $( find "$dir" -name *.tex ) );
+  fi
 }
 
 # attempts to compile multiple .tex files
 function __latex.compile.all {
-	local file;
-	for file in "${latex_files[@]}"
-		do
-			__latex.compile "$file";
-	done
+  local file;
+  for file in "${latex_files[@]}"
+    do
+      __latex.compile "$file";
+  done
 }
 
 # attempts to compile a single .tex source file
 function __latex.compile {
-	local name nm parent target output="$latex_output";
-	fs.basename "$file" "name";
-	nm="${name%.tex}";
-	
-	fs.dirname "$file" "parent";
-	# target used to cd into so that external files
-	# are resolved relative to the source .tex file
-	target="${parent}";
-	# make parent realtive to latex_dir
-	parent="${parent#$latex_dir}";
+  local name nm parent target output="$latex_output";
+  fs.basename "$file" "name";
+  nm="${name%.tex}";
+  
+  fs.dirname "$file" "parent";
+  # target used to cd into so that external files
+  # are resolved relative to the source .tex file
+  target="${parent}";
+  # make parent realtive to latex_dir
+  parent="${parent#$latex_dir}";
 
-	# echo "compiling with dir: $latex_dir";
-	# echo "compiling with file: $file";
-	# echo "compiling with parent: $parent";
-	
-	# if parent is empty the output is the root
-	if [ -n "$parent" ]; then
-		output="${output}${parent}";
-		
-		if [ ! -d "$output" ]; then
-			mkdir -p "$output" || console quit 1 "could not create output directory %s" "$output";
-		fi
-	fi
-	
-	latex_options[0]="-output-directory=$output";
-	
-	# echo "using output: $output";
-	
-	if $latex_debug; then
-		console print "${executables[pdflatex]} ${latex_options[*]} %s" "$file";
-	fi
+  # echo "compiling with dir: $latex_dir";
+  # echo "compiling with file: $file";
+  # echo "compiling with parent: $parent";
+  
+  # if parent is empty the output is the root
+  if [ -n "$parent" ]; then
+    output="${output}${parent}";
+    
+    if [ ! -d "$output" ]; then
+      mkdir -p "$output" || console quit 1 "could not create output directory %s" "$output";
+    fi
+  fi
+  
+  latex_options[0]="-output-directory=$output";
+  
+  # echo "using output: $output";
+  
+  if $latex_debug; then
+    console print "${executables[pdflatex]} ${latex_options[*]} %s" "$file";
+  fi
 
-	local logfile="${output}/${nm}.compile.log";
-	
-	# exit code from compilation
-	local owd=$( pwd );
-	# run in subshell so the `cd` does no affect working
-	# directory of the parent shell
-	cd "${target}" || console quit 1 "could not cd to %s" "${target}";
-	# TODO: quote options passed to latex to allow spaces in file paths
-	"${executables[pdflatex]}" "${latex_options[@]:-}" "$file" >| "$logfile" 2>&1;
-	if [ $? -gt 0 ]; then
-		if $latex_debug; then
-			if [ -f "${output}/${nm}.log" ]; then
-				# latex generated log file, more verbose/informative
-				cat "${output}/${nm}.log" >&2;
-			else
-				cat "$logfile" >&2;
-			fi
-		fi
-		console warn "log file %s" "${output}/${nm}.log";
-		console warn "log file %s" "$logfile";
-		console quit 1 "failed to compile %s" "$file";
-	fi
-	cd "$owd" || console quit 1 "could not cd to %s" "${owd}";
+  local logfile="${output}/${nm}.compile.log";
+  
+  # exit code from compilation
+  local owd=$( pwd );
+  # run in subshell so the `cd` does no affect working
+  # directory of the parent shell
+  cd "${target}" || console quit 1 "could not cd to %s" "${target}";
+  # TODO: quote options passed to latex to allow spaces in file paths
+  "${executables[pdflatex]}" "${latex_options[@]:-}" "$file" >| "$logfile" 2>&1;
+  if [ $? -gt 0 ]; then
+    if $latex_debug; then
+      if [ -f "${output}/${nm}.log" ]; then
+        # latex generated log file, more verbose/informative
+        cat "${output}/${nm}.log" >&2;
+      else
+        cat "$logfile" >&2;
+      fi
+    fi
+    console warn "log file %s" "${output}/${nm}.log";
+    console warn "log file %s" "$logfile";
+    console quit 1 "failed to compile %s" "$file";
+  fi
+  cd "$owd" || console quit 1 "could not cd to %s" "${owd}";
 }
 
 # parse command line options
 function __latex.parse {
-	# unprocessed options
-	local options=();
-	
-	# listing the pdflatex options
-	# allows us to add our own options
-	# and validate the options parsed before
-	# invoking pdflatex, will need a resync
-	# when new versions of pdflatex are released
-	# the boolean value indicates whether the pdflatex
-	# option expects a value using the = operator
-	declare -A latex_options=(
-		[-draftmode]=false
-		[-enc]=false
-		[-etex]=false
-		[file-line-error]=false
-		[-no-file-line-error]=false
-		[-fmt]=true
-		[-ini]=false
-		[-interaction]=true
-		[-ipc]=false
-		[-ipc-start]=false
-		[-jobname]=true
-		[-kpathsea-debug]=true
-		[mktex]=true
-		[-no-mktex]=true		
-		[-mltex]=false
-		[-output-comment]=true
-		[-no-parse-first-line]=false
-		[-progname]=true
-		[-recorder]=false
-		[-shell-escape]=false
-		[-no-shell-escape]=false
-		[-shell-restricted]=false
-		[-src-specials]=false
-		[-src-specials]=true
-		[-synctex]=true
-		[-translate-file]=true
-		[-8bit]=false
-	);
+  # unprocessed options
+  local options=();
+  
+  # listing the pdflatex options
+  # allows us to add our own options
+  # and validate the options parsed before
+  # invoking pdflatex, will need a resync
+  # when new versions of pdflatex are released
+  # the boolean value indicates whether the pdflatex
+  # option expects a value using the = operator
+  declare -A latex_options=(
+    [-draftmode]=false
+    [-enc]=false
+    [-etex]=false
+    [file-line-error]=false
+    [-no-file-line-error]=false
+    [-fmt]=true
+    [-ini]=false
+    [-interaction]=true
+    [-ipc]=false
+    [-ipc-start]=false
+    [-jobname]=true
+    [-kpathsea-debug]=true
+    [mktex]=true
+    [-no-mktex]=true    
+    [-mltex]=false
+    [-output-comment]=true
+    [-no-parse-first-line]=false
+    [-progname]=true
+    [-recorder]=false
+    [-shell-escape]=false
+    [-no-shell-escape]=false
+    [-shell-restricted]=false
+    [-src-specials]=false
+    [-src-specials]=true
+    [-synctex]=true
+    [-translate-file]=true
+    [-8bit]=false
+  );
 
-	# unsupported pdflatex(1) options
-	
-	# [-output-directory]=true
-	# [-output-format]=true
-	# [-halt-on-error]=false
-	# -help
-	# -version
-	
-	local value;
-	# handle other options
-	while [ "${1:-}" != "" ]; do
-		case $1 in
-			-d | --dir )
-				shift;
-				value="${1:-}";
-				if [ -z "$value" ]; then
-					console quit 1 "no directory specified for the %s option" "-d | --dir";
-				fi
-				if [ ! -d "$value" ]; then
-					console quit 1 "%s not a directory" "$value";
-				fi
-				if [ ! -r "$value" ]; then
-					console quit 1 "%s not readable" "$value";
-				fi
-				latex_dir="$value";
-				;;
-			-o | --output )
-				shift;
-				value="${1:-}";
-				if [ -z "$value" ]; then
-					console quit 1 "no directory specified for the %s option" "-o | --output";
-				fi
-				if [ ! -d "$value" ] || [ ! -w "$value" ]; then
-					console quit 1 "invalid output directory %s" "$value";
-				fi
-				# remove any trailing slash
-				value="${value%/}";
-				latex_output="$value";
-				;;
-			--debug )
-				latex_debug=true;
-				;;					
-			* )
-				options+=( "$1" );
-				;;
-		esac
-		if [ $# -ne 0 ]; then
-			shift;
-		else
-			break;
-		fi
-	done
+  # unsupported pdflatex(1) options
+  
+  # [-output-directory]=true
+  # [-output-format]=true
+  # [-halt-on-error]=false
+  # -help
+  # -version
+  
+  local value;
+  # handle other options
+  while [ "${1:-}" != "" ]; do
+    case $1 in
+      -d | --dir )
+        shift;
+        value="${1:-}";
+        if [ -z "$value" ]; then
+          console quit 1 "no directory specified for the %s option" "-d | --dir";
+        fi
+        if [ ! -d "$value" ]; then
+          console quit 1 "%s not a directory" "$value";
+        fi
+        if [ ! -r "$value" ]; then
+          console quit 1 "%s not readable" "$value";
+        fi
+        latex_dir="$value";
+        ;;
+      -o | --output )
+        shift;
+        value="${1:-}";
+        if [ -z "$value" ]; then
+          console quit 1 "no directory specified for the %s option" "-o | --output";
+        fi
+        if [ ! -d "$value" ] || [ ! -w "$value" ]; then
+          console quit 1 "invalid output directory %s" "$value";
+        fi
+        # remove any trailing slash
+        value="${value%/}";
+        latex_output="$value";
+        ;;
+      --debug )
+        latex_debug=true;
+        ;;          
+      * )
+        options+=( "$1" );
+        ;;
+    esac
+    if [ $# -ne 0 ]; then
+      shift;
+    else
+      break;
+    fi
+  done
 
-	# return remaining options back
-	_result="${options[@]:-}";
+  # return remaining options back
+  _result="${options[@]:-}";
 }
diff --git a/lib/modules/tasks/todo b/lib/modules/tasks/todo
--- a/lib/modules/tasks/todo
+++ b/lib/modules/tasks/todo
@@ -11,468 +11,468 @@ help.man.page "todo" "task-todo.7";
 # TODO: reintegrate the ignore patterns with the file listing logic
 declare -ag todo_ignore_patterns;
 todo_ignore_patterns=(
-	"\.log$"
-	"\.tmp$"
-	"\.bak$"
-	"/\.git/?.*$"
-	"\.gitignore$"
-	"/target/?.*$"
-	"/test/?.*$"
-	"/man/?.*$"
-	"/doc/?.*$"
-	"/tmp/?.*$"
-	"\.DS_Store$"
-	"/package.json$"
-	"/semver.json$"
-	"/version$"
-	"/tasks$"
-	"/AUTHORS$"
-	"/CHANGES$"
-	"/LICENSE$"
-	"/INSTALL$"
-	"/README\.?.*$"
-	"/Rakefile$"
+  "\.log$"
+  "\.tmp$"
+  "\.bak$"
+  "/\.git/?.*$"
+  "\.gitignore$"
+  "/target/?.*$"
+  "/test/?.*$"
+  "/man/?.*$"
+  "/doc/?.*$"
+  "/tmp/?.*$"
+  "\.DS_Store$"
+  "/package.json$"
+  "/semver.json$"
+  "/version$"
+  "/tasks$"
+  "/AUTHORS$"
+  "/CHANGES$"
+  "/LICENSE$"
+  "/INSTALL$"
+  "/README\.?.*$"
+  "/Rakefile$"
 );
 
 declare -ag todo_dirs;
 todo_dirs=(
-	"bin"
-	"lib"
-	"src"
+  "bin"
+  "lib"
+  "src"
 );
 
 declare -Ag todo_tags;
-todo_tags[fixme]="FIX ?ME[ 	,:]+[ 	]*(.*)";
-todo_tags[bug]="BUG[ 	,:]+[ 	]*(.*)";
-todo_tags[todo]="TODO[ 	,:]+[ 	]*(.*)";
-todo_tags[note]="NOTE[ 	,:]+[ 	]*(.*)";
-todo_tags[xxx]="XXX[ 	,:]+[ 	]*(.*)";
-todo_tags[deprecated]="DEPRECATED[ 	,:]+[ 	]*(.*)";
-todo_tags[changed]="CHANGED[ 	,:]+[ 	]*(.*)";
+todo_tags[fixme]="FIX ?ME[  ,:]+[   ]*(.*)";
+todo_tags[bug]="BUG[  ,:]+[   ]*(.*)";
+todo_tags[todo]="TODO[  ,:]+[   ]*(.*)";
+todo_tags[note]="NOTE[  ,:]+[   ]*(.*)";
+todo_tags[xxx]="XXX[  ,:]+[   ]*(.*)";
+todo_tags[deprecated]="DEPRECATED[  ,:]+[   ]*(.*)";
+todo_tags[changed]="CHANGED[  ,:]+[   ]*(.*)";
 
 taskinfo todo "Scan for todo comments";
 tasks.todo() {
-	executable.validate find;
-	
-	echo "$FUNCNAME";
-	
-	# list of files to scan
-	declare -a files;
-	files=();
-	
-	# custom list of dirs to scan
-	# specified with --dir
-	declare -a scandirs;
-	scandirs=();	
-	
-	# custom list of files to scan
-	# specified with --file
-	declare -a scanfiles;
-	scanfiles=();
-	
-	# custom tags to search for
-	declare -a tags;
-	tags=();
-	
-	# list of all tag keys
-	# used internally
-	declare -a all_tags=( ${!todo_tags[@]} );
-	
-	local include_symlinks=false;
-	local silent=false;
-	
-	__todo.options.parse "$@";
-	
-	# custom tag filters
-	if [ ${#tags[@]} -gt 0 ]; then
-		local k;
-		for k in ${!todo_tags[@]}
-			do
-				if ! array.contains? "$k" "${tags[@]}"; then
-					unset todo_tags[$k];
-				fi
-		done
-	fi
-	
-	# set up counters
-	declare -A count;
-	for k in ${all_tags[@]}
-		do
-			count[$k]=0;
-	done
-	
-	# do command procesing via delegation
-	if [ $# -gt 0 ]; then
-		local method="td.${FUNCNAME}.${1}";
-		if ! method.exists? "$method"; then
-			console quit 1 "invalid todo command %s" "$1";
-		else
-			delegate "td.${FUNCNAME}" "$1" ${@:2};
-		fi
-	else
-		# no options specified scan files
-		td.tasks.todo.scan;
-	fi
+  executable.validate find;
+  
+  echo "$FUNCNAME";
+  
+  # list of files to scan
+  declare -a files;
+  files=();
+  
+  # custom list of dirs to scan
+  # specified with --dir
+  declare -a scandirs;
+  scandirs=();  
+  
+  # custom list of files to scan
+  # specified with --file
+  declare -a scanfiles;
+  scanfiles=();
+  
+  # custom tags to search for
+  declare -a tags;
+  tags=();
+  
+  # list of all tag keys
+  # used internally
+  declare -a all_tags=( ${!todo_tags[@]} );
+  
+  local include_symlinks=false;
+  local silent=false;
+  
+  __todo.options.parse "$@";
+  
+  # custom tag filters
+  if [ ${#tags[@]} -gt 0 ]; then
+    local k;
+    for k in ${!todo_tags[@]}
+      do
+        if ! array.contains? "$k" "${tags[@]}"; then
+          unset todo_tags[$k];
+        fi
+    done
+  fi
+  
+  # set up counters
+  declare -A count;
+  for k in ${all_tags[@]}
+    do
+      count[$k]=0;
+  done
+  
+  # do command procesing via delegation
+  if [ $# -gt 0 ]; then
+    local method="td.${FUNCNAME}.${1}";
+    if ! method.exists? "$method"; then
+      console quit 1 "invalid todo command %s" "$1";
+    else
+      delegate "td.${FUNCNAME}" "$1" ${@:2};
+    fi
+  else
+    # no options specified scan files
+    td.tasks.todo.scan;
+  fi
 }
 
 # print tags
 function td.tasks.todo.tags {
-	local k p;
-	for k in ${!todo_tags[@]}
-		do
-			p="${todo_tags[$k]}";
-			k="${k^^}";
-			__todo.log "$k=$p";
-	done
-	__todo.exit;
+  local k p;
+  for k in ${!todo_tags[@]}
+    do
+      p="${todo_tags[$k]}";
+      k="${k^^}";
+      __todo.log "$k=$p";
+  done
+  __todo.exit;
 }
 
 # print ignore patterns
 function td.tasks.todo.excludes {
-	local p
-	for p in ${todo_ignore_patterns[@]}
-		do
-			__todo.log "$p";
-	done
-	__todo.exit;
+  local p
+  for p in ${todo_ignore_patterns[@]}
+    do
+      __todo.log "$p";
+  done
+  __todo.exit;
 }
 
 # list matched files
 function td.tasks.todo.list {
-	__todo.log "# todo list ${root}";
-	__todo.list;
-	for f in ${files[@]}	
-		do
-			__todo.log "$f";
-	done
-	__todo.log "# ${#files[@]} files";
-	__todo.exit;
+  __todo.log "# todo list ${root}";
+  __todo.list;
+  for f in ${files[@]}  
+    do
+      __todo.log "$f";
+  done
+  __todo.log "# ${#files[@]} files";
+  __todo.exit;
 }
 
 # scan and gather tag information
 function td.tasks.todo.scan {
-	__todo.log "# todo scan %s" "${root}";
-	__todo.list;
-	for f in ${files[@]}
-		do
-			# echo "scanning file $f";
-			__todo.scan.file "$f";
-	done
-	__todo.summary;
-	__todo.exit;
+  __todo.log "# todo scan %s" "${root}";
+  __todo.list;
+  for f in ${files[@]}
+    do
+      # echo "scanning file $f";
+      __todo.scan.file "$f";
+  done
+  __todo.summary;
+  __todo.exit;
 }
 
 # count tags
 function td.tasks.todo.count {
-	silent=true;
-	__todo.list;
-	for f in ${files[@]}
-		do
-			__todo.scan.file "$f";
-	done
-	__todo.count;
-	__todo.exit;
+  silent=true;
+  __todo.list;
+  for f in ${files[@]}
+    do
+      __todo.scan.file "$f";
+  done
+  __todo.count;
+  __todo.exit;
 }
 
 ######################################################################
 #
-#	PRIVATE METHODS
+# PRIVATE METHODS
 #
 ######################################################################
 
 # parse options
 function __todo.options.parse {
-	
-	# remove command option
-	shift;
-	
-	# build up tag option comparison
-	local tag_opts=();
-	for k in ${all_tags[@]}
-		do
-			tags_opts+=( "--${k}" );
-	done
-	
-	# handle custom tag filter flags
-	local k;
-	for k in ${!todo_tags[@]}
-		do
-			if array.contains? "--${k}" "$@"; then
-				tags+=( "$k" );
-			fi
-	done
-	
-	# handle other options
-	while [ "${1:-}" != "" ]; do
-		if array.contains? "$1" "${tags_opts[@]}"; then
-			shift;
-			continue;
-		fi
-		case $1 in
-			--silent )
-				silent=true;
-				;;				
-			--file )
-				shift;
-				local file="${1:-}";
-				if [ -z "$file" ]; then
-					console quit 1 "no file specified to %s" "--file";
-				fi
-				if [[ ! "$file" =~ ^(\.+)?/ ]]; then
-					file="${root}/${file}";
-				fi
-				if [ ! -f "$file" ]; then
-					console warn "file %s is invalid" "$file";
-				else
-					fs.path.expand "$file";
-					file="$_result";
-					# add to custom list of files to scan
-					scanfiles+=( "$file" );
-				fi
-				;;
-			# TOOD: make this option resolve absolute file paths like the --file option
-			--dir )
-				shift;
-				local dir="${1:-}";
-				if [ -z "$dir" ]; then
-					console quit 1 "no directory specified to %s" "--dir";
-				fi
-				dir="${dir#/}";
-				dir="${root}/${dir}";
-				if [ -d "${dir}" ]; then
-					scandirs+=( "$1" );
-				else
- 					console warn "invalid scan directory %s" "$dir";
-				fi
-				;;
-			* )
-				console warn "usage: todo [command] [options...]";
-				console quit 1 "unkown option %s" "$1";
-				;;
-		esac
-		if [ $# -ne 0 ]; then
-			shift;
-		else
-			break;
-		fi
-	done
+  
+  # remove command option
+  shift;
+  
+  # build up tag option comparison
+  local tag_opts=();
+  for k in ${all_tags[@]}
+    do
+      tags_opts+=( "--${k}" );
+  done
+  
+  # handle custom tag filter flags
+  local k;
+  for k in ${!todo_tags[@]}
+    do
+      if array.contains? "--${k}" "$@"; then
+        tags+=( "$k" );
+      fi
+  done
+  
+  # handle other options
+  while [ "${1:-}" != "" ]; do
+    if array.contains? "$1" "${tags_opts[@]}"; then
+      shift;
+      continue;
+    fi
+    case $1 in
+      --silent )
+        silent=true;
+        ;;        
+      --file )
+        shift;
+        local file="${1:-}";
+        if [ -z "$file" ]; then
+          console quit 1 "no file specified to %s" "--file";
+        fi
+        if [[ ! "$file" =~ ^(\.+)?/ ]]; then
+          file="${root}/${file}";
+        fi
+        if [ ! -f "$file" ]; then
+          console warn "file %s is invalid" "$file";
+        else
+          fs.path.expand "$file";
+          file="$_result";
+          # add to custom list of files to scan
+          scanfiles+=( "$file" );
+        fi
+        ;;
+      # TOOD: make this option resolve absolute file paths like the --file option
+      --dir )
+        shift;
+        local dir="${1:-}";
+        if [ -z "$dir" ]; then
+          console quit 1 "no directory specified to %s" "--dir";
+        fi
+        dir="${dir#/}";
+        dir="${root}/${dir}";
+        if [ -d "${dir}" ]; then
+          scandirs+=( "$1" );
+        else
+          console warn "invalid scan directory %s" "$dir";
+        fi
+        ;;
+      * )
+        console warn "usage: todo [command] [options...]";
+        console quit 1 "unkown option %s" "$1";
+        ;;
+    esac
+    if [ $# -ne 0 ]; then
+      shift;
+    else
+      break;
+    fi
+  done
 }
 
 function __todo.excludes? {
-	local replace="${2:-}";
-	local file="$1";
-	if [ -n "$replace" ]; then
-		# remove any trailing slash from the replacement
-		replace="${replace/\$/}";
-		file="${file#$replace}";
-	fi
-	
-	# echo "testing exclude on $1 with ${#todo_ignore_patterns[@]}";
-	local p;
-	for p in ${todo_ignore_patterns[@]}
-		do	
-			# skip symbolic links
-			if ! $include_symlinks && [ -L "$1" ]; then
-				# echo "omitting symlink $1";
-				return 0;				
-			fi
-			# skip on pattern match
-			if [[ "$file" =~ $p ]]; then
-				# echo "excluded : $file on $p";
-				return 0;
-			fi
-	done
-	return 1;
+  local replace="${2:-}";
+  local file="$1";
+  if [ -n "$replace" ]; then
+    # remove any trailing slash from the replacement
+    replace="${replace/\$/}";
+    file="${file#$replace}";
+  fi
+  
+  # echo "testing exclude on $1 with ${#todo_ignore_patterns[@]}";
+  local p;
+  for p in ${todo_ignore_patterns[@]}
+    do  
+      # skip symbolic links
+      if ! $include_symlinks && [ -L "$1" ]; then
+        # echo "omitting symlink $1";
+        return 0;       
+      fi
+      # skip on pattern match
+      if [[ "$file" =~ $p ]]; then
+        # echo "excluded : $file on $p";
+        return 0;
+      fi
+  done
+  return 1;
 }
 
 # use `find` to locate files to scan
 function __todo.find {
-	files+=( $( "${executables[find]}" "$1" -type f ) );
+  files+=( $( "${executables[find]}" "$1" -type f ) );
 }
 
 # build scan directories relative to ${root}
 function __todo.find.dirs {
-	local dir;
-	for dir in $@
-		do
-			dir="${dir#/}";
-			dir="${root}/${dir}";
-			if [ -d "$dir" ]; then
-				__todo.find "$dir";
-			fi
-	done
+  local dir;
+  for dir in $@
+    do
+      dir="${dir#/}";
+      dir="${root}/${dir}";
+      if [ -d "$dir" ]; then
+        __todo.find "$dir";
+      fi
+  done
 }
 
 # get all files
 function __todo.list {
-	# default scan
-	if [ ${#scanfiles} -eq 0 ] && [ ${#scandirs[@]} -eq 0 ]; then
-		__todo.find.dirs "${todo_dirs[@]}";
-	else
-		if [ ${#scanfiles[@]} -gt 0 ]; then
-			files+=( ${scanfiles[@]} );
-		fi
-		if [ ${#scandirs[@]} -gt 0 ]; then
-			__todo.find.dirs ${scandirs[@]};
-		fi
-	fi
+  # default scan
+  if [ ${#scanfiles} -eq 0 ] && [ ${#scandirs[@]} -eq 0 ]; then
+    __todo.find.dirs "${todo_dirs[@]}";
+  else
+    if [ ${#scanfiles[@]} -gt 0 ]; then
+      files+=( ${scanfiles[@]} );
+    fi
+    if [ ${#scandirs[@]} -gt 0 ]; then
+      __todo.find.dirs ${scandirs[@]};
+    fi
+  fi
 }
 
 # test if a line matches a tag pattern
 function __todo.line.matches? {
-	local p;
-	for tag in ${!todo_tags[@]}
-		do	
-			p="${todo_tags[$tag]}";
-			if [ -n "$p" ]; then
-				# echo "matching line with  $p : $line";
-				if [[ "$line" =~ $p ]]; then
-					todo="${BASH_REMATCH[1]:-}";
-					frame="${file}:${lineno}";
-					tag="${tag^^}";
-					string.ltrim "$todo";
-					todo="${_result}";			
-					#__todo.output;
-					return 0;
-				fi
-			fi
-	done
-	tag="";
-	return 1;
+  local p;
+  for tag in ${!todo_tags[@]}
+    do  
+      p="${todo_tags[$tag]}";
+      if [ -n "$p" ]; then
+        # echo "matching line with  $p : $line";
+        if [[ "$line" =~ $p ]]; then
+          todo="${BASH_REMATCH[1]:-}";
+          frame="${file}:${lineno}";
+          tag="${tag^^}";
+          string.ltrim "$todo";
+          todo="${_result}";      
+          #__todo.output;
+          return 0;
+        fi
+      fi
+  done
+  tag="";
+  return 1;
 }
 
 # scan a file
 function __todo.scan.file {
-	# console info "scanning %s" "$1";
-	local file="$1";	
-	local lineno=0;
-	local tag frame todo;
-	
-	# linked list style to maintain order
-	declare -a matchindex;
-	declare -A filematches;
-	__todo.scan.file.add()
-	{
-		local key="${tag}:${frame}";
-		filematches["$key"]="${todo}";
-		matchindex+=( "$key" );
-	}
-	
-	while IFS= read -r line
-		do	
-			__todo.line;
-	done < "$file";
-	# process last line
-	if [ -n "$line" ]; then __todo.line; fi
-		
-	# got some matches print them
-	if [ ${#filematches[@]} -gt 0 ]; then
-		__todo.print;
-	fi
-	
-	# clean inner method definitions
-	method.remove __todo.scan.file.add;
+  # console info "scanning %s" "$1";
+  local file="$1";  
+  local lineno=0;
+  local tag frame todo;
+  
+  # linked list style to maintain order
+  declare -a matchindex;
+  declare -A filematches;
+  __todo.scan.file.add()
+  {
+    local key="${tag}:${frame}";
+    filematches["$key"]="${todo}";
+    matchindex+=( "$key" );
+  }
+  
+  while IFS= read -r line
+    do  
+      __todo.line;
+  done < "$file";
+  # process last line
+  if [ -n "$line" ]; then __todo.line; fi
+    
+  # got some matches print them
+  if [ ${#filematches[@]} -gt 0 ]; then
+    __todo.print;
+  fi
+  
+  # clean inner method definitions
+  method.remove __todo.scan.file.add;
 }
 
 #print matches
 function __todo.print {
-	local k matches last_lineno=0;
-	local len=$(( ${#filematches[@]} - 1 ));
-	for k in ${matchindex[@]}
-		do
-			#echo "got key : $k";
-			local IFS=":";
-			matches=( $k );
-			unset IFS;
-			tag="${matches[0]}";	
-			lineno="${matches[1]}";
-			frame="${matches[2]}";
-			# 
-			todo="${filematches[$k]}";
-			
-			#echo "got todo: $todo"
-		
-			# if [ $i -lt $len ]; then
-			# 	#echo "check for next match ... ";
-			# fi
-			echo "got match: $i : $tag : $lineno : $frame";
-			
-			last_lineno=$lineno;
-	done
+  local k matches last_lineno=0;
+  local len=$(( ${#filematches[@]} - 1 ));
+  for k in ${matchindex[@]}
+    do
+      #echo "got key : $k";
+      local IFS=":";
+      matches=( $k );
+      unset IFS;
+      tag="${matches[0]}";  
+      lineno="${matches[1]}";
+      frame="${matches[2]}";
+      # 
+      todo="${filematches[$k]}";
+      
+      #echo "got todo: $todo"
+    
+      # if [ $i -lt $len ]; then
+      #   #echo "check for next match ... ";
+      # fi
+      echo "got match: $i : $tag : $lineno : $frame";
+      
+      last_lineno=$lineno;
+  done
 }
 
 # process a line in the file
 function __todo.line {
-	: $((lineno++));	
-	# test for tag matches
-	if __todo.line.matches? "$line"; then
-		# add the match
-		#__todo.scan.file.add;
-		
-		__todo.output;
-		
-		# increment counters
-		__todo.increment;
-	fi
+  : $((lineno++));  
+  # test for tag matches
+  if __todo.line.matches? "$line"; then
+    # add the match
+    #__todo.scan.file.add;
+    
+    __todo.output;
+    
+    # increment counters
+    __todo.increment;
+  fi
 }
 
 # log output
 function __todo.log {
-	if ! $silent; then
-		console print "$@";
-	fi
+  if ! $silent; then
+    console print "$@";
+  fi
 }
 
 function __todo.increment {
-	local countkey="${tag,,}";
-	: $(( count["$countkey"]++ ));	
+  local countkey="${tag,,}";
+  : $(( count["$countkey"]++ ));  
 }
 
 # output todo tag information
 function __todo.output {
-	#echo "incrementing count on tag: $tag";
-	if ! $silent; then
-		if [ "$tag" == "BUG" ] || [ "$tag" == "FIXME" ]; then		
-			echo "# $tag $frame" >&2;
-			echo "$todo" >&2;
-		else		
-			console print "# %s %s" "$tag" "$frame";
-			console print "$todo";
-		fi
-	fi
+  #echo "incrementing count on tag: $tag";
+  if ! $silent; then
+    if [ "$tag" == "BUG" ] || [ "$tag" == "FIXME" ]; then   
+      echo "# $tag $frame" >&2;
+      echo "$todo" >&2;
+    else    
+      console print "# %s %s" "$tag" "$frame";
+      console print "$todo";
+    fi
+  fi
 }
 
 # print the count summary
 function __todo.summary {
-	if ! $silent; then
-		string.repeat "+" 80;
-		local header="$_result";	
-		echo "$header";
-		__todo.count;
-		echo "$header";
-	fi
+  if ! $silent; then
+    string.repeat "+" 80;
+    local header="$_result";  
+    echo "$header";
+    __todo.count;
+    echo "$header";
+  fi
 }
 
 function __todo.count {
-	local k v;
-	for k in ${!count[@]}
-		do
-			# tag filtering
-			if [ ${#tags[@]} -gt 0 ] && ! array.contains? "$k" "${tags[@]}"; then
-				continue;
-			fi
-			v="${count[$k]}";
-			k="${k^^}";
-			echo "$k=$v";
-	done
+  local k v;
+  for k in ${!count[@]}
+    do
+      # tag filtering
+      if [ ${#tags[@]} -gt 0 ] && ! array.contains? "$k" "${tags[@]}"; then
+        continue;
+      fi
+      v="${count[$k]}";
+      k="${k^^}";
+      echo "$k=$v";
+  done
 }
 
 #exit program
 function __todo.exit {
-	if [ ${#count[bug]} -gt 0 ] || [ ${#count[fixme]} -gt 0 ]; then
-		local total=$(( ${count[bug]} + ${count[fixme]} ));
-		console quit $total;
-	else
-		console quit 0;
-	fi
+  if [ ${#count[bug]} -gt 0 ] || [ ${#count[fixme]} -gt 0 ]; then
+    local total=$(( ${count[bug]} + ${count[fixme]} ));
+    console quit $total;
+  else
+    console quit 0;
+  fi
 }
diff --git a/lib/modules/util/checksum b/lib/modules/util/checksum
--- a/lib/modules/util/checksum
+++ b/lib/modules/util/checksum
@@ -1,44 +1,44 @@
 # generate a checksum using either
 # shasum or sha1sum
 checksum.sha() {
-	local algorithm="512";
-	if [[ "${1:-}" =~ ^[0-9]+$ ]]; then
-		algorithm="$1";
-		shift;
-	fi
-	local target="sha${algorithm}sum";
-	local binaries=( shasum "${target}" );
-	executable.validate --test "${binaries[@]}";
-	local exe="${executables[shasum]}";
-	# --portable --binary ?
-	local opts=( --algorithm $algorithm );
-	if [ -z "${exe}" ]; then
-		exe="${executables[${target}]}";
-		opts="";
-	fi
-	if [ -z "${exe}" ]; then
-		console warn "cannot generate sha checksum missing one of %s" \
-			"${binaries[*]}";
-		return 1;
-	else
-		"$exe" ${opts[@]:-} $@;
-		return $?;
-	fi
+  local algorithm="512";
+  if [[ "${1:-}" =~ ^[0-9]+$ ]]; then
+    algorithm="$1";
+    shift;
+  fi
+  local target="sha${algorithm}sum";
+  local binaries=( shasum "${target}" );
+  executable.validate --test "${binaries[@]}";
+  local exe="${executables[shasum]}";
+  # --portable --binary ?
+  local opts=( --algorithm $algorithm );
+  if [ -z "${exe}" ]; then
+    exe="${executables[${target}]}";
+    opts="";
+  fi
+  if [ -z "${exe}" ]; then
+    console warn "cannot generate sha checksum missing one of %s" \
+      "${binaries[*]}";
+    return 1;
+  else
+    "$exe" ${opts[@]:-} $@;
+    return $?;
+  fi
 }
 
 # generate a md5 checksum using either
 # md5 (BSD) or md5sum (Linux)
 checksum.md5() {
-	local file="${1:-}";
-	if [ -z "$file" ]; then
-		return 1;
-	fi
-	local binaries=( md5 md5sum );
-	executable.validate --test "${binaries[@]}";
-	if [ -n "${executables[md5]}" ]; then
-		${executables[md5]} -q "$file";
-	elif [ -n "${executables[md5sum]}" ]; then
-		local parts=( $( ${executables[md5sum]} "$file" ) );
-		printf "${parts[0]}\n";
-	fi
+  local file="${1:-}";
+  if [ -z "$file" ]; then
+    return 1;
+  fi
+  local binaries=( md5 md5sum );
+  executable.validate --test "${binaries[@]}";
+  if [ -n "${executables[md5]}" ]; then
+    ${executables[md5]} -q "$file";
+  elif [ -n "${executables[md5sum]}" ]; then
+    local parts=( $( ${executables[md5sum]} "$file" ) );
+    printf "${parts[0]}\n";
+  fi
 }
