Added the console.log.* methods for redirecting console messages to a log file and closing the file descriptors (reinstating the previous stdout/stderr) and added the appropriate unit tests.

diff --git a/lib/modules/console b/lib/modules/console
--- a/lib/modules/console
+++ b/lib/modules/console
@@ -92,15 +92,49 @@ ronn:markdown
 
 
 
+declare -gx __stdout_log_file="";
+declare -gx __stderr_log_file="";
 
+function console.log.stdout {
+	touch "$1" || warn "could not create stdout log file %s" "$1";
+	if [ -f "$1" ]; then
+		__stdout_log_file="$1";		
+		# save stdout in file descriptor #3
+		exec 3>&1;
+		exec 1>> "$1";
+	fi
+}
 
+function console.log.stdout.close {
+	if [ ! -z "$__stdout_log_file" ]; then
+		# restore stdout and close file descriptor #3
+		exec 1>&3 3>&- || console.warn "no file descriptor for stdout log file";
+		__stdout_log_file="";
+	fi
+}
 
+function console.log.stderr {
+	touch "$1" || warn "could not create stderr log file %s" "$1";
+	if [ -f "$1" ]; then
+		__stderr_log_file="$1";
+		# save stderr in file descriptor #4
+		exec 4>&2;
+		exec 2>> "$1";
+	fi
+}
 
-
-
-
-
-
+function console.log.stderr.close {
+	
+	# TODO: potential test for an open file descriptor?
+	# requires testing cross-platform
+	# ls -la /dev/fd/4
+	
+	if [ ! -z "$__stderr_log_file" ]; then
+		# restore stdout and close file descriptor #3
+		exec 2>&4 4>&- || console.warn "no file descriptor for stderr log file";
+		__stderr_log_file="";
+	fi
+}
 
 
 ######################################################################
