Added round trip creation and extraction unit tests for the tar type of task-archive(7).

diff --git a/lib/modules/fs b/lib/modules/fs
--- a/lib/modules/fs
+++ b/lib/modules/fs
@@ -217,21 +217,21 @@ function validate_rmdir {
 #
 #	$1 		The path to the directory.
 ######################################################################
-function rmdir {
-	local dir="$1";
-	validate_rmdir "$dir";	
-	fs.path.expand "$dir";
-	dir=$_result;
-	validate_rmdir "$dir";
-	rm -rf "$dir";
-	if [ $? -eq 0 ]; then
-			info "$REMOVED_DIRECTORY" "$dir";
-			return 0;
-		else
-			error "$DIRECTORY_REMOVE_FAIL" "$dir";
-			return 1;
-	fi
-}
+# function rmdir {
+# 	local dir="$1";
+# 	validate_rmdir "$dir";	
+# 	fs.path.expand "$dir";
+# 	dir=$_result;
+# 	validate_rmdir "$dir";
+# 	rm -rf "$dir";
+# 	if [ $? -eq 0 ]; then
+# 			info "$REMOVED_DIRECTORY" "$dir";
+# 			return 0;
+# 		else
+# 			error "$DIRECTORY_REMOVE_FAIL" "$dir";
+# 			return 1;
+# 	fi
+# }
 
 ######################################################################
 #	Attempts to remove a directory as the root user.
