Added the --show-error option when executing curl and redirected the curl stderr to a file which is output when a non-zero exit code is detected.

diff --git a/lib/modules/http b/lib/modules/http
--- a/lib/modules/http
+++ b/lib/modules/http
@@ -17,6 +17,7 @@ export http_trace_ascii_file="$http_home/http.trace.ascii";
 export http_head_dump_file="$http_home/http.head.dump";
 export http_config_dir="$http_home/config";
 export http_config_file="$http_home/http.config";
+export http_error_file="$http_home/http.err";
 export http_config_name="";
 export http_base_url="";
 
@@ -91,7 +92,7 @@ function http.curl.execute {
 	#http_response_exit_code=0;
 	
 	set +o errexit;	
-	results=( $( $cmd "${runopts[@]}" || echo -n "$?" >> "$http_exit_file" ) );
+	results=( $( $cmd "${runopts[@]}" 2> "$http_error_file" || echo -n "$?" >> "$http_exit_file" ) );
 	curl_exit_code=0;
 	
 	if [ -f "$http_exit_file" ]; then
@@ -99,7 +100,7 @@ function http.curl.execute {
 		curl_exit_code=${curl_exit_code:-0};
 	fi
 	
-	echo "got curl exit code: $curl_exit_code";
+	# echo "got curl exit code: $curl_exit_code";
 	
 	if [ ${#results[@]} -gt 2 ]; then
 		http_response_status="${results[0]}";
@@ -114,11 +115,17 @@ function http.curl.execute {
 	fi
 	
 	if [ "$http_response_exit_code" != "0" ]; then
-		
 		if [ ! -z "$http_strict" ]; then
+			if [ -f "$http_error_file" ]; then
+				error "`cat $http_error_file`";
+			fi
 			quit $http_response_exit_code "curl exited with non-zero status code (%s)" "$http_response_exit_code";
 		else
-			warn "curl exited with non-zero status code (%s)" "$http_response_exit_code";
+			if [ -f "$http_error_file" ]; then
+				warn "`cat $http_error_file`";
+			else
+				warn "curl exited with non-zero status code (%s" "$http_response_exit_code";
+			fi
 		fi
 	fi
 	
@@ -172,6 +179,7 @@ function http_curl {
 		"--request"
 		"${method}"
 		"--silent"
+		"--show-error"
 		"--location"
 		"--include"
 	);
