Improved name rule validation for project and profile names in the deploy task.

diff --git a/lib/modules/tasks/deploy b/lib/modules/tasks/deploy
--- a/lib/modules/tasks/deploy
+++ b/lib/modules/tasks/deploy
@@ -164,6 +164,9 @@ tasks.deploy() {
 
 	executable.validate --test growlnotify;
 	
+	# name validation regex
+	local re="^[-a-zA-Z0-9]+$";
+	
 	# non-operation
 	local noop=false;
 
@@ -590,9 +593,27 @@ EOF
 	fi
 }
 
+:tasks.name.valid?() {
+	local name="${1:-}";
+	# may not start with a hyphen
+	# and must match the name regex
+	if [[ "$name" =~ ^-+ ]] || [[ ! "$name" =~ $re ]]; then
+		return 1;
+	fi
+	return 0;
+}
+
+:tasks.name.quit() {
+	local var="$1";
+	local value="$2";
+	console.error "names may not start with a hyphen and must match %s" "$re";	
+	console.error "invalid $var name %s" "$value";
+	console.quit 1;
+}
+
 # parse options
 :tasks.deploy.options.parse() {
-	local value re="^[-a-zA-Z0-9]+$";
+	local value ;
 	while test -n "${1:-}"; do
 		case $1 in
 			--noop )
@@ -618,8 +639,8 @@ EOF
 				if [ -z "${value}" ]; then
 					console.quit 1 "no name specified";
 				fi
-				if [[ ! "$value" =~ $re ]]; then
-					console.quit 1 "invalid project name %s must match %s" "$value" "$re";
+				if ! :tasks.name.valid? "${value}"; then
+					:tasks.name.quit "project" "$value";
 				fi
 				project_name="${value}";
 				;;
@@ -640,11 +661,11 @@ EOF
 				descriptor="${value}";		
 				;;
 			-* | --* )
-				console.quit 1 "invalid option %s" "$1";
+				console.quit 1 "unknown option %s" "$1";
 				;;
 			* )
-				if [[ ! "$1" =~ $re ]]; then
-					console.quit 1 "invalid profile name %s must match %s" "$1" "$re";
+				if ! :tasks.name.valid? "$1"; then
+					:tasks.name.quit "profile" "$1";
 				fi
 				profiles+=( "$1" );
 				;;
